POST http://13.125.141.7:8888/login
Content-Type: application/json

{
  "email": "a1010100z",
  "password": "1234"
}

###
POST http://13.125.141.7:8888/login
Content-Type: application/json

{
  "email": "a1010100zz",
  "password": "1234"
}

###

POST http://13.125.141.7:8888/board
Content-Type: application/json


{
  "subject": "제목입니다",
  "contents": "내용입니다"
}
